### ISSUE TITLE
Kanban Set Up

### ISSUE THREAD

**Issue by shihabrafio** [shihabrafio/Catalog-App#26]
Here is the link of [Github Project](https://github.com/shihabrafio/Catalog-App/projects/1)
We are two people in here Rafio & Gakii
#Team Member 1 - @shihabrafio
#Team Member 2 - @berylcl

**Comment by Abenezer-Tilahun** [comment]
Hi @shihabrafio @berylcl 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ Good job for Provide the information about the number of people in their group.
✔️ Good Job for Provide link to their GitHub project.
✔️ Good Job for Implementing Ruby group capstone: set up your Kanban board .
## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
